services:
  db:
    image: mysql
    command: --max_connections=200
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=skill-report
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
  deployment:
    image: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./target/skill-report-1.0.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - db
    restart: unless-stopped
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
#  session-store:
#    image: redis
#    ports:
#      - 6379:6379
#    environment:
#      - REDIS_PASSWORD=root
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
#    volumes:
#      - session-store-data:/data
#  session-gui:
#    image: redislabs/redisinsight
#    ports:
#      - 8001:8001
#    volumes:
#      - session-gui-data:/db
#    depends_on:
#      - session-store
volumes:
  db_data:
#  session-store-data:
#  session-gui-data: